name: methyl-microc
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.11
  - nextflow
  - nf-core
  
  # Core methylation analysis tools
  - bwameth=0.2.7
  - bwa=0.7.18
  - trim-galore=0.6.10
  - fastqc=0.12.1
  - multiqc=1.30
  - samtools=1.21
  - bedtools=2.31.1
  - picard=3.4.0
  - qualimap=2.3
  - methyldackel=0.7.0
  
  # Additional alignment and processing tools
  - hisat2=2.2.1
  - minimap2=2.30
  - cutadapt=5.1
  
  # Compression and utilities
  - pigz=2.8
  - pbzip2=1.1.13
  
  # Python packages for analysis
  - matplotlib
  - numpy
  - pandas
  - scipy
  - pyyaml
  - jinja2
  - click
  - coloredlogs
  - markdown
  - future
  - spectra
  - rich
  - lzstring
  
  # R packages for statistical analysis
  - r-base=4.4.3
  - r-optparse
  - r-ggplot2
  - r-reshape2
  - r-scales
  - r-pheatmap
  - r-lattice
  - r-gplots
  - bioconductor-biobase
  - bioconductor-biocgenerics
  - bioconductor-genomicranges
  - bioconductor-iranges
  - bioconductor-rsamtools
  - bioconductor-rtracklayer
  - bioconductor-biostrings
  - bioconductor-genomicalignments
  
  # Additional utilities
  - gzip
  - tar
  - wget
  - curl
